baseURL = "https://gc4camp.github.io/public/"
title = "ç™½æ¿æŠ¥"
copyright = "Copyright Â© 2019, Wangpei"
languageCode = "zh-CN"
theme = "indigo"
paginate = 5

[params]
  Author = "Wangpei"
  Description = "ä¸€ä¸ªæŠ€æœ¯åšå®¢"
  Subtitle = "A subtitle for your site"
  Avatar = "images/hugo-logo.png"
  Biography = "A short description, a few sentences describing the author. Set the 'ShowBio' parameter to false to hide this."
  ShowBio = false
  PermalinkText = "ğŸ”—"

  # Contact/social-network identifiers for social icons
  EmailAddress = "i@wangpei.org"
  FacebookUser = "FacebookUserName"
  FlickrUser = "FlickrUserName"
  GitHubUser = "shipian"
  GitLabUser = "GitLabUserName"
  GlitchUser = "GlitchUserName"
  KeybaseUser = "KeybaseUserName"
  LinkedInUser = "LinkedInUserName"
  MediumUser = "wangpei"
  MicroBlogUser = "MicroBlogUserName"
  RedditUser = "RedditUserName"
  StackOverflowUser = "StackOverflowUserName"
  TumblrUser = "TumblrUserName"
  TwitterUser = "wangpei"

  # These are parameters used for indieweb identity. You should set these along
  # with the above email/social network parameters.
  [params.indieWeb]  
    EmailAddress = "i@wangpei.org"
    FlickrUser = "FlickrUserName"
    GitHubUser = "shipian"
    TwitterUser = "wangpei"
    MicroBlogUser = "MicroBlogUserName"
    Country = "China"
    City = "Hangzhou"
